### ISSUE TITLE
Adding support for nodes connected via lan

### ISSUE THREAD

**Issue by ddthekidd** [RCGV1/Meshtastic-SAME-EAS-Alerter#1]
I can't connect my node via serial because I have to use a PD adapter (Station G2) but if I could use a node connected to my LAN then this program would work for me.  If you could add this as an option that would be amazing.  Thanks!

**Comment by RCGV1** [comment]
Thanks for the suggestion, I will work on adding TCP connection support.

**Comment by ddthekidd** [comment]
Thank you very much!!

**Comment by RCGV1** [comment]
TCP connection is now supported
